//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 03:04:21 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://ipgw.testbsp.com.pg/sabre", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = { @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://localhost:9091/sabre", prefix = "") })
package com.truteq.ccpgw.payment.gateway.api.soap;
