//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import com.truteq.ccpgw.payment.gateway.api.soap.AdditionalDetailType;
import com.truteq.ccpgw.payment.gateway.api.soap.AddressType;
import com.truteq.ccpgw.payment.gateway.api.soap.AccountDetailType;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentMethod" type="{}PaymentMethodType" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="PaymentCard" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{}PaymentCardType">
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="BankAccount" type="{}AccountDetailType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="BillingAddress" type="{}AddressType" minOccurs="0"/>
 *         &lt;element name="AmountDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CurrencyAmountType">
 *                 &lt;sequence>
 *                   &lt;element name="TaxBreak" type="{}TaxType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="FeeBreak" type="{}FeeBreakType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InstallmentDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="NumberOfInstallments" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="InstallmentAmount" type="{}Money" />
 *                 &lt;attribute name="InterestAmount" type="{}Money" />
 *                 &lt;attribute name="Plan" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PromotionalInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="GroupCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReturnURLs" type="{}ReturnURLsType" minOccurs="0"/>
 *         &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
 *         &lt;element name="DCC" type="{}DCCType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentDetailType", propOrder = {
    "paymentMethod",
    "paymentCard",
    "bankAccount",
    "billingAddress",
    "amountDetail",
    "installmentDetail",
    "returnURLs",
    "additionalDetail",
    "dcc"
})
public class PaymentDetailType {

    @XmlElement(name = "PaymentMethod")
    protected PaymentMethodType paymentMethod;
    @XmlElement(name = "PaymentCard")
    protected PaymentDetailType.PaymentCard paymentCard;
    @XmlElement(name = "BankAccount")
    protected AccountDetailType bankAccount;
    @XmlElement(name = "BillingAddress")
    protected AddressType billingAddress;
    @XmlElement(name = "AmountDetail")
    protected PaymentDetailType.AmountDetail amountDetail;
    @XmlElement(name = "InstallmentDetail")
    protected PaymentDetailType.InstallmentDetail installmentDetail;
    @XmlElement(name = "ReturnURLs")
    protected ReturnURLsType returnURLs;
    @XmlElement(name = "AdditionalDetail")
    protected AdditionalDetailType additionalDetail;
    @XmlElement(name = "DCC")
    protected DCCType dcc;

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodType }
     *     
     */
    public PaymentMethodType getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodType }
     *     
     */
    public void setPaymentMethod(PaymentMethodType value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the paymentCard property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.PaymentCard }
     *     
     */
    public PaymentDetailType.PaymentCard getPaymentCard() {
        return paymentCard;
    }

    /**
     * Sets the value of the paymentCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.PaymentCard }
     *     
     */
    public void setPaymentCard(PaymentDetailType.PaymentCard value) {
        this.paymentCard = value;
    }

    /**
     * Gets the value of the bankAccount property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetailType }
     *     
     */
    public AccountDetailType getBankAccount() {
        return bankAccount;
    }

    /**
     * Sets the value of the bankAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetailType }
     *     
     */
    public void setBankAccount(AccountDetailType value) {
        this.bankAccount = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setBillingAddress(AddressType value) {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the amountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.AmountDetail }
     *     
     */
    public PaymentDetailType.AmountDetail getAmountDetail() {
        return amountDetail;
    }

    /**
     * Sets the value of the amountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.AmountDetail }
     *     
     */
    public void setAmountDetail(PaymentDetailType.AmountDetail value) {
        this.amountDetail = value;
    }

    /**
     * Gets the value of the installmentDetail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetailType.InstallmentDetail }
     *     
     */
    public PaymentDetailType.InstallmentDetail getInstallmentDetail() {
        return installmentDetail;
    }

    /**
     * Sets the value of the installmentDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetailType.InstallmentDetail }
     *     
     */
    public void setInstallmentDetail(PaymentDetailType.InstallmentDetail value) {
        this.installmentDetail = value;
    }

    /**
     * Gets the value of the returnURLs property.
     * 
     * @return
     *     possible object is
     *     {@link ReturnURLsType }
     *     
     */
    public ReturnURLsType getReturnURLs() {
        return returnURLs;
    }

    /**
     * Sets the value of the returnURLs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReturnURLsType }
     *     
     */
    public void setReturnURLs(ReturnURLsType value) {
        this.returnURLs = value;
    }

    /**
     * Gets the value of the additionalDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDetailType }
     *     
     */
    public AdditionalDetailType getAdditionalDetail() {
        return additionalDetail;
    }

    /**
     * Sets the value of the additionalDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDetailType }
     *     
     */
    public void setAdditionalDetail(AdditionalDetailType value) {
        this.additionalDetail = value;
    }

    /**
     * Gets the value of the dcc property.
     * 
     * @return
     *     possible object is
     *     {@link DCCType }
     *     
     */
    public DCCType getDCC() {
        return dcc;
    }

    /**
     * Sets the value of the dcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCCType }
     *     
     */
    public void setDCC(DCCType value) {
        this.dcc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CurrencyAmountType">
     *       &lt;sequence>
     *         &lt;element name="TaxBreak" type="{}TaxType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="FeeBreak" type="{}FeeBreakType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxBreak",
        "feeBreak"
    })
    public static class AmountDetail
        extends CurrencyAmountType
    {

        @XmlElement(name = "TaxBreak")
        protected List<TaxType> taxBreak;
        @XmlElement(name = "FeeBreak")
        protected FeeBreakType feeBreak;

        /**
         * Gets the value of the taxBreak property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taxBreak property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaxBreak().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TaxType }
         * 
         * 
         */
        public List<TaxType> getTaxBreak() {
            if (taxBreak == null) {
                taxBreak = new ArrayList<TaxType>();
            }
            return this.taxBreak;
        }

        /**
         * Gets the value of the feeBreak property.
         * 
         * @return
         *     possible object is
         *     {@link FeeBreakType }
         *     
         */
        public FeeBreakType getFeeBreak() {
            return feeBreak;
        }

        /**
         * Sets the value of the feeBreak property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeeBreakType }
         *     
         */
        public void setFeeBreak(FeeBreakType value) {
            this.feeBreak = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="NumberOfInstallments" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="InstallmentAmount" type="{}Money" />
     *       &lt;attribute name="InterestAmount" type="{}Money" />
     *       &lt;attribute name="Plan" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PromotionalInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="GroupCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InstallmentDetail {

        @XmlAttribute(name = "NumberOfInstallments", required = true)
        protected String numberOfInstallments;
        @XmlAttribute(name = "InstallmentAmount")
        protected BigDecimal installmentAmount;
        @XmlAttribute(name = "InterestAmount")
        protected BigDecimal interestAmount;
        @XmlAttribute(name = "Plan")
        protected String plan;
        @XmlAttribute(name = "PromotionalInd")
        protected Boolean promotionalInd;
        @XmlAttribute(name = "Type")
        protected String type;
        @XmlAttribute(name = "Code")
        protected String code;
        @XmlAttribute(name = "GroupCode")
        protected String groupCode;

        /**
         * Gets the value of the numberOfInstallments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumberOfInstallments() {
            return numberOfInstallments;
        }

        /**
         * Sets the value of the numberOfInstallments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumberOfInstallments(String value) {
            this.numberOfInstallments = value;
        }

        /**
         * Gets the value of the installmentAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInstallmentAmount() {
            return installmentAmount;
        }

        /**
         * Sets the value of the installmentAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInstallmentAmount(BigDecimal value) {
            this.installmentAmount = value;
        }

        /**
         * Gets the value of the interestAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getInterestAmount() {
            return interestAmount;
        }

        /**
         * Sets the value of the interestAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setInterestAmount(BigDecimal value) {
            this.interestAmount = value;
        }

        /**
         * Gets the value of the plan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlan() {
            return plan;
        }

        /**
         * Sets the value of the plan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlan(String value) {
            this.plan = value;
        }

        /**
         * Gets the value of the promotionalInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isPromotionalInd() {
            return promotionalInd;
        }

        /**
         * Sets the value of the promotionalInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPromotionalInd(Boolean value) {
            this.promotionalInd = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the groupCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroupCode() {
            return groupCode;
        }

        /**
         * Sets the value of the groupCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroupCode(String value) {
            this.groupCode = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}PaymentCardType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PaymentCard
        extends PaymentCardType
    {


    }

}
