//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Point of Sales information.
 * 
 * <p>Java class for POS_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POS_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BrowserDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="HttpHeaders" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="HttpHeader" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BrowserJavaEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="BrowserJavascriptEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="BrowserScreenColorDepth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="BrowserScreenHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="BrowserScreenWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="BrowserTimeZoneOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="ChallengeWindowSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CountryCode" use="required" type="{}ISO3166" />
 *       &lt;attribute name="ChannelID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IP_Address" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StationNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POS_Type", propOrder = {
    "browserDetail"
})
public class POSType {

    @XmlElement(name = "BrowserDetail")
    protected POSType.BrowserDetail browserDetail;
    @XmlAttribute(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlAttribute(name = "ChannelID", required = true)
    protected String channelID;
    @XmlAttribute(name = "IP_Address")
    protected String ipAddress;
    @XmlAttribute(name = "StationNumber")
    protected String stationNumber;

    /**
     * Gets the value of the browserDetail property.
     * 
     * @return
     *     possible object is
     *     {@link POSType.BrowserDetail }
     *     
     */
    public POSType.BrowserDetail getBrowserDetail() {
        return browserDetail;
    }

    /**
     * Sets the value of the browserDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSType.BrowserDetail }
     *     
     */
    public void setBrowserDetail(POSType.BrowserDetail value) {
        this.browserDetail = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the channelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelID() {
        return channelID;
    }

    /**
     * Sets the value of the channelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelID(String value) {
        this.channelID = value;
    }

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPAddress(String value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the stationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationNumber() {
        return stationNumber;
    }

    /**
     * Sets the value of the stationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationNumber(String value) {
        this.stationNumber = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="HttpHeaders" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="HttpHeader" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="BrowserJavaEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="BrowserJavascriptEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="BrowserScreenColorDepth" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="BrowserScreenHeight" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="BrowserScreenWidth" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="BrowserTimeZoneOffset" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="ChallengeWindowSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "httpHeaders"
    })
    public static class BrowserDetail {

        @XmlElement(name = "HttpHeaders")
        protected POSType.BrowserDetail.HttpHeaders httpHeaders;
        @XmlAttribute(name = "BrowserJavaEnabled")
        protected Boolean browserJavaEnabled;
        @XmlAttribute(name = "BrowserJavascriptEnabled")
        protected Boolean browserJavascriptEnabled;
        @XmlAttribute(name = "BrowserScreenColorDepth")
        protected BigInteger browserScreenColorDepth;
        @XmlAttribute(name = "BrowserScreenHeight")
        protected BigInteger browserScreenHeight;
        @XmlAttribute(name = "BrowserScreenWidth")
        protected BigInteger browserScreenWidth;
        @XmlAttribute(name = "BrowserTimeZoneOffset")
        protected BigInteger browserTimeZoneOffset;
        @XmlAttribute(name = "ChallengeWindowSize")
        protected BigInteger challengeWindowSize;

        /**
         * Gets the value of the httpHeaders property.
         * 
         * @return
         *     possible object is
         *     {@link POSType.BrowserDetail.HttpHeaders }
         *     
         */
        public POSType.BrowserDetail.HttpHeaders getHttpHeaders() {
            return httpHeaders;
        }

        /**
         * Sets the value of the httpHeaders property.
         * 
         * @param value
         *     allowed object is
         *     {@link POSType.BrowserDetail.HttpHeaders }
         *     
         */
        public void setHttpHeaders(POSType.BrowserDetail.HttpHeaders value) {
            this.httpHeaders = value;
        }

        /**
         * Gets the value of the browserJavaEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBrowserJavaEnabled() {
            return browserJavaEnabled;
        }

        /**
         * Sets the value of the browserJavaEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBrowserJavaEnabled(Boolean value) {
            this.browserJavaEnabled = value;
        }

        /**
         * Gets the value of the browserJavascriptEnabled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isBrowserJavascriptEnabled() {
            return browserJavascriptEnabled;
        }

        /**
         * Sets the value of the browserJavascriptEnabled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setBrowserJavascriptEnabled(Boolean value) {
            this.browserJavascriptEnabled = value;
        }

        /**
         * Gets the value of the browserScreenColorDepth property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrowserScreenColorDepth() {
            return browserScreenColorDepth;
        }

        /**
         * Sets the value of the browserScreenColorDepth property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrowserScreenColorDepth(BigInteger value) {
            this.browserScreenColorDepth = value;
        }

        /**
         * Gets the value of the browserScreenHeight property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrowserScreenHeight() {
            return browserScreenHeight;
        }

        /**
         * Sets the value of the browserScreenHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrowserScreenHeight(BigInteger value) {
            this.browserScreenHeight = value;
        }

        /**
         * Gets the value of the browserScreenWidth property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrowserScreenWidth() {
            return browserScreenWidth;
        }

        /**
         * Sets the value of the browserScreenWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrowserScreenWidth(BigInteger value) {
            this.browserScreenWidth = value;
        }

        /**
         * Gets the value of the browserTimeZoneOffset property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBrowserTimeZoneOffset() {
            return browserTimeZoneOffset;
        }

        /**
         * Sets the value of the browserTimeZoneOffset property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBrowserTimeZoneOffset(BigInteger value) {
            this.browserTimeZoneOffset = value;
        }

        /**
         * Gets the value of the challengeWindowSize property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getChallengeWindowSize() {
            return challengeWindowSize;
        }

        /**
         * Sets the value of the challengeWindowSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setChallengeWindowSize(BigInteger value) {
            this.challengeWindowSize = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="HttpHeader" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "httpHeader"
        })
        public static class HttpHeaders {

            @XmlElement(name = "HttpHeader", required = true)
            protected List<POSType.BrowserDetail.HttpHeaders.HttpHeader> httpHeader;

            /**
             * Gets the value of the httpHeader property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the httpHeader property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHttpHeader().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link POSType.BrowserDetail.HttpHeaders.HttpHeader }
             * 
             * 
             */
            public List<POSType.BrowserDetail.HttpHeaders.HttpHeader> getHttpHeader() {
                if (httpHeader == null) {
                    httpHeader = new ArrayList<POSType.BrowserDetail.HttpHeaders.HttpHeader>();
                }
                return this.httpHeader;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
             *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class HttpHeader {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "Name", required = true)
                protected String name;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

            }

        }

    }

}
