/*
 * ***************************************************************
 * Credit Card Payment Gateway (IPGW) version 1.0.0
 * ***************************************************************
 * Copyright (c) 2021 Truteq Australia 2019
 * ***************************************************************
 * CCPGW Transaction Manager: POSTILION - Transaction Manager  
 * Support: Grant O'Reilly gbo@truteq.com
 * V01.00.00  30-Jul-2021 
 * ***************************************************************
 */
package com.truteq.ccpgw.transaction.manager.model;

import com.google.gson.Gson;

/**
 *
 * @author mho
 */

public class MerchantCurrencyMap {

    private String merchantName;
    private String merchantNo;
    private String terminalNo;
    private String currency;
    private String emailAddress;
    private String autoGeneratedMid;
    private String autoGeneratedTid;
    private String mcc;
    private String merchantAccountCode;
    private String code;
    private String cardAcceptorNameLocation;
    private String stationNumber;

    public String toJSON() {
        Gson gson = new Gson();
        return gson.toJson(this);
    }

    /**
     * @return the merchantName
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * @param merchantName the merchantName to set
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * @return the merchantNo
     */
    public String getMerchantNo() {
        return merchantNo;
    }

    /**
     * @param merchantNo the merchantNo to set
     */
    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * @return the terminalNo
     */
    public String getTerminalNo() {
        return terminalNo;
    }

    /**
     * @param terminalNo the terminalNo to set
     */
    public void setTerminalNo(String terminalNo) {
        this.terminalNo = terminalNo;
    }

    /**
     * @return the currency
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * @param currency the currency to set
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * @return the emailAddress
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * @param emailAddress the emailAddress to set
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * @return the autoGeneratedMid
     */
    public String getAutoGeneratedMid() {
        return autoGeneratedMid;
    }

    /**
     * @param autoGeneratedMid the autoGeneratedMid to set
     */
    public void setAutoGeneratedMid(String autoGeneratedMid) {
        this.autoGeneratedMid = autoGeneratedMid;
    }

    /**
     * @return the autoGeneratedTid
     */
    public String getAutoGeneratedTid() {
        return autoGeneratedTid;
    }

    /**
     * @param autoGeneratedTid the autoGeneratedTid to set
     */
    public void setAutoGeneratedTid(String autoGeneratedTid) {
        this.autoGeneratedTid = autoGeneratedTid;
    }

    /**
     * @return the mcc
     */
    public String getMcc() {
        return mcc;
    }

    /**
     * @param mcc the mcc to set
     */
    public void setMcc(String mcc) {
        this.mcc = mcc;
    }

    /**
     * @return the merchantAccountCode
     */
    public String getMerchantAccountCode() {
        return merchantAccountCode;
    }

    /**
     * @param merchantAccountCode the merchantAccountCode to set
     */
    public void setMerchantAccountCode(String merchantAccountCode) {
        this.merchantAccountCode = merchantAccountCode;
    }

    /**
     * @return the code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the code to set
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * @return the cardAcceptorNameLocation
     */
    public String getCardAcceptorNameLocation() {
        return cardAcceptorNameLocation;
    }

    /**
     * @param cardAcceptorNameLocation the cardAcceptorNameLocation to set
     */
    public void setCardAcceptorNameLocation(String cardAcceptorNameLocation) {
        this.cardAcceptorNameLocation = cardAcceptorNameLocation;
    }

    /**
     * @return the stationNumber
     */
    public String getStationNumber() {
        return stationNumber;
    }

    /**
     * @param stationNumber the stationNumber to set
     */
    public void setStationNumber(String stationNumber) {
        this.stationNumber = stationNumber;
    }
}
