//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 01:49:42 PM AEST 
//


package com.truteq.ccpgw.netcetera.model;

import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *           
 *             The PaReqCreationRequest passed to MPI for the createPaReqIfEnrolled call.
 *           
 *         
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Cardholder" type="{http://mpi.netcetera.com}Cardholder" minOccurs="0"/>
 *         &lt;element name="Purchase" type="{http://mpi.netcetera.com}Purchase" minOccurs="0"/>
 *         &lt;element name="Merchant" type="{http://mpi.netcetera.com}Merchant" minOccurs="0"/>
 *         &lt;element name="Browser" type="{http://mpi.netcetera.com}Browser" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "Cardholder",
    "Purchase",
    "Merchant",
    "Browser",
    "extension"
})
@XmlRootElement(name = "PaReqCreationRequest", namespace = "http://mpi.netcetera.com")
public class PaReqCreationRequest {

    @XmlElement(name = "Cardholder")
    protected Cardholder Cardholder;
    @XmlElement(name = "Purchase")
    protected Purchase Purchase;
    @XmlElement(name = "Merchant")
    protected Merchant Merchant;
    @XmlElement(name = "Browser")
    protected Browser Browser;
    @XmlElement(name = "Extension")
    protected List<Object> Extension;

    
    public String toJSON(){
        Gson gson =new Gson();
        return gson.toJson(this);
    }
    
    /**
     * Gets the value of the Cardholder property.
     * 
     * @return
     *     possible object is
     *     {@link Cardholder }
     *     
     */
    public Cardholder getCardholder() {
        return Cardholder;
    }

    /**
     * Sets the value of the Cardholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cardholder }
     *     
     */
    public void setCardholder(Cardholder value) {
        this.Cardholder = value;
    }

    /**
     * Gets the value of the Purchase property.
     * 
     * @return
     *     possible object is
     *     {@link Purchase }
     *     
     */
    public Purchase getPurchase() {
        return Purchase;
    }

    /**
     * Sets the value of the Purchase property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purchase }
     *     
     */
    public void setPurchase(Purchase value) {
        this.Purchase = value;
    }

    /**
     * Gets the value of the Merchant property.
     * 
     * @return
     *     possible object is
     *     {@link Merchant }
     *     
     */
    public Merchant getMerchant() {
        return Merchant;
    }

    /**
     * Sets the value of the Merchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Merchant }
     *     
     */
    public void setMerchant(Merchant value) {
        this.Merchant = value;
    }

    /**
     * Gets the value of the Browser property.
     * 
     * @return
     *     possible object is
     *     {@link Browser }
     *     
     */
    public Browser getBrowser() {
        return Browser;
    }

    /**
     * Sets the value of the Browser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Browser }
     *     
     */
    public void setBrowser(Browser value) {
        this.Browser = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getExtension() {
        if (Extension == null) {
            Extension = new ArrayList<Object>();
        }
        return this.Extension;
    }

}
