/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.truteq.ccpgw.threeds.v2.objects.versioning;

import java.util.Map;

/**
 *
 * @author Grant Blaise O'Reilly <gbo@truteq.com>
 */
public class Sdk {
 
    public Sdk(){

    }    
    
    public Sdk(String sdkAppID,
               String sdkEncData,
               Integer sdkMaxTimeout,
               String sdkReferenceNumber,
               String sdkTransID,
               Map<String, Object> sdkEphemPubKey){
        this();
        this.sdkAppID = sdkAppID;
        this.sdkEncData = sdkEncData;
        this.sdkMaxTimeout = sdkMaxTimeout;
        this.sdkReferenceNumber = sdkReferenceNumber;
        this.sdkTransID = sdkTransID;
        this.sdkEphemPubKey = sdkEphemPubKey;
        
    }     
  /**
   * Universally unique ID created upon all installations and updates of the 3DS Requestor App on a Customer Device.
   * This will be newly generated and stored by the 3DS SDK for each installation or update. The field is limited to 36
   * characters and it shall have a canonical format as defined in IETF RFC 4122. This may utilise any of the specified
   * versions as long as the output meets specified requirements.
   */
  private String sdkAppID;
  /**
   * JWE Object as defined Section 6.2.2.1 containing data encrypted by the SDK for the DS to decrypt. This element is
   * the only field encrypted in this version of the EMV 3-D Secure specification. The field is sent from the SDK and it
   * is limited to 64.000 characters. The data will be present when sending to DS, but not present from DS to ACS.
   */
  private String sdkEncData;
  /**
   * Public key component of the ephemeral key pair generated by the 3DS SDK and used to establish session keys between
   * the 3DS SDK and ACS. In AReq, this data element is contained within the ACS Signed Content JWS Object. The field is
   * limited to maximum 256 characters.
   */
  private Map<String, Object> sdkEphemPubKey;
  /**
   * Indicates the maximum amount of time (in minutes) for all exchanges. The field shall have value greater or equals
   * than 05.
   */
  private Integer sdkMaxTimeout;
  /**
   * Identifies the vendor and version of the 3DS SDK that is integrated in a 3DS Requestor App, assigned by EMVCo when
   * the 3DS SDK is approved. The field is limited to 32 characters.
   */
  private String sdkReferenceNumber;
  /**
   * Universally unique transaction identifier assigned by the 3DS SDK to identify a single transaction. The field is
   * limited to 36 characters and it shall be in a canonical format as defined in IETF RFC 4122. This may utilise any of
   * the specified versions as long as the output meets specific requirements.
   */
  private String sdkTransID;

    /**
     * @return the sdkAppID
     */
    public String getSdkAppID() {
        return sdkAppID;
    }

    /**
     * @param sdkAppID the sdkAppID to set
     */
    public void setSdkAppID(String sdkAppID) {
        this.sdkAppID = sdkAppID;
    }

    /**
     * @return the sdkEncData
     */
    public String getSdkEncData() {
        return sdkEncData;
    }

    /**
     * @param sdkEncData the sdkEncData to set
     */
    public void setSdkEncData(String sdkEncData) {
        this.sdkEncData = sdkEncData;
    }

    /**
     * @return the sdkEphemPubKey
     */
    public Map<String, Object> getSdkEphemPubKey() {
        return sdkEphemPubKey;
    }

    /**
     * @param sdkEphemPubKey the sdkEphemPubKey to set
     */
    public void setSdkEphemPubKey(Map<String, Object> sdkEphemPubKey) {
        this.sdkEphemPubKey = sdkEphemPubKey;
    }

    /**
     * @return the sdkMaxTimeout
     */
    public Integer getSdkMaxTimeout() {
        return sdkMaxTimeout;
    }

    /**
     * @param sdkMaxTimeout the sdkMaxTimeout to set
     */
    public void setSdkMaxTimeout(Integer sdkMaxTimeout) {
        this.sdkMaxTimeout = sdkMaxTimeout;
    }

    /**
     * @return the sdkReferenceNumber
     */
    public String getSdkReferenceNumber() {
        return sdkReferenceNumber;
    }

    /**
     * @param sdkReferenceNumber the sdkReferenceNumber to set
     */
    public void setSdkReferenceNumber(String sdkReferenceNumber) {
        this.sdkReferenceNumber = sdkReferenceNumber;
    }

    /**
     * @return the sdkTransID
     */
    public String getSdkTransID() {
        return sdkTransID;
    }

    /**
     * @param sdkTransID the sdkTransID to set
     */
    public void setSdkTransID(String sdkTransID) {
        this.sdkTransID = sdkTransID;
    }
}