//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="POS" type="{}POS_Type"/>
 *         &lt;element name="OrderDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ProductDetail" type="{}ProductDetailType" minOccurs="0"/>
 *                   &lt;element name="PassengerDetail" type="{}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="FlightDetail" type="{}FlightDetailType" maxOccurs="20" minOccurs="0"/>
 *                   &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="RecordLocator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ConfirmationNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="OrderExpireDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PaymentDetail" type="{}PaymentDetailType" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="CustomerDetail" type="{}CustomerDetailType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MerchantAccountCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RequestID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pos",
    "orderDetail",
    "paymentDetail",
    "customerDetail"
})
@XmlRootElement(name = "AuthRQ")
public class AuthRQ {

    @XmlElement(name = "POS", required = true)
    protected POSType pos;
    @XmlElement(name = "OrderDetail")
    protected AuthRQ.OrderDetail orderDetail;
    @XmlElement(name = "PaymentDetail")
    protected List<PaymentDetailType> paymentDetail;
    @XmlElement(name = "CustomerDetail")
    protected CustomerDetailType customerDetail;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "MerchantAccountCode", required = true)
    protected String merchantAccountCode;
    @XmlAttribute(name = "RequestID")
    protected String requestID;
    @XmlAttribute(name = "SessionID")
    private String sessionid;
    @XmlAttribute(name = "OrderNumber")
    private String orderNumber;

    
    public String toJSON() {
        Gson gson = new Gson();
        return gson.toJson(this);
    }    
    
    
    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link POSType }
     *     
     */
    public POSType getPOS() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link POSType }
     *     
     */
    public void setPOS(POSType value) {
        this.pos = value;
    }

    /**
     * Gets the value of the orderDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AuthRQ.OrderDetail }
     *     
     */
    public AuthRQ.OrderDetail getOrderDetail() {
        return orderDetail;
    }

    /**
     * Sets the value of the orderDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthRQ.OrderDetail }
     *     
     */
    public void setOrderDetail(AuthRQ.OrderDetail value) {
        this.orderDetail = value;
    }

    /**
     * Gets the value of the paymentDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentDetailType }
     * 
     * 
     */
    public List<PaymentDetailType> getPaymentDetail() {
        if (paymentDetail == null) {
            paymentDetail = new ArrayList<PaymentDetailType>();
        }
        return this.paymentDetail;
    }

    /**
     * Gets the value of the customerDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerDetailType }
     *     
     */
    public CustomerDetailType getCustomerDetail() {
        return customerDetail;
    }

    /**
     * Sets the value of the customerDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerDetailType }
     *     
     */
    public void setCustomerDetail(CustomerDetailType value) {
        this.customerDetail = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the merchantAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAccountCode() {
        return merchantAccountCode;
    }

    /**
     * Sets the value of the merchantAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAccountCode(String value) {
        this.merchantAccountCode = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ProductDetail" type="{}ProductDetailType" minOccurs="0"/>
     *         &lt;element name="PassengerDetail" type="{}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="FlightDetail" type="{}FlightDetailType" maxOccurs="20" minOccurs="0"/>
     *         &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="RecordLocator" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ConfirmationNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="OrderExpireDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "productDetail",
        "passengerDetail",
        "flightDetail",
        "additionalDetail"
    })
    public static class OrderDetail {

        @XmlElement(name = "ProductDetail")
        protected ProductDetailType productDetail;
        @XmlElement(name = "PassengerDetail")
        protected List<PassengerDetailType> passengerDetail;
        @XmlElement(name = "FlightDetail")
        protected List<FlightDetailType> flightDetail;
        @XmlElement(name = "AdditionalDetail")
        protected AdditionalDetailType additionalDetail;
        @XmlAttribute(name = "OrderNumber")
        protected String orderNumber;
        @XmlAttribute(name = "RecordLocator")
        protected String recordLocator;
        @XmlAttribute(name = "ConfirmationNumber")
        protected String confirmationNumber;
        @XmlAttribute(name = "OrderExpireDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar orderExpireDateTime;

        /**
         * Gets the value of the productDetail property.
         * 
         * @return
         *     possible object is
         *     {@link ProductDetailType }
         *     
         */
        public ProductDetailType getProductDetail() {
            return productDetail;
        }

        /**
         * Sets the value of the productDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link ProductDetailType }
         *     
         */
        public void setProductDetail(ProductDetailType value) {
            this.productDetail = value;
        }

        /**
         * Gets the value of the passengerDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassengerDetailType }
         * 
         * 
         */
        public List<PassengerDetailType> getPassengerDetail() {
            if (passengerDetail == null) {
                passengerDetail = new ArrayList<PassengerDetailType>();
            }
            return this.passengerDetail;
        }

        /**
         * Gets the value of the flightDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flightDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlightDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightDetailType }
         * 
         * 
         */
        public List<FlightDetailType> getFlightDetail() {
            if (flightDetail == null) {
                flightDetail = new ArrayList<FlightDetailType>();
            }
            return this.flightDetail;
        }

        /**
         * Gets the value of the additionalDetail property.
         * 
         * @return
         *     possible object is
         *     {@link AdditionalDetailType }
         *     
         */
        public AdditionalDetailType getAdditionalDetail() {
            return additionalDetail;
        }

        /**
         * Sets the value of the additionalDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdditionalDetailType }
         *     
         */
        public void setAdditionalDetail(AdditionalDetailType value) {
            this.additionalDetail = value;
        }

        /**
         * Gets the value of the orderNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderNumber() {
            return orderNumber;
        }

        /**
         * Sets the value of the orderNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderNumber(String value) {
            this.orderNumber = value;
        }

        /**
         * Gets the value of the recordLocator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRecordLocator() {
            return recordLocator;
        }

        /**
         * Sets the value of the recordLocator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRecordLocator(String value) {
            this.recordLocator = value;
        }

        /**
         * Gets the value of the confirmationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConfirmationNumber() {
            return confirmationNumber;
        }

        /**
         * Sets the value of the confirmationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConfirmationNumber(String value) {
            this.confirmationNumber = value;
        }

        /**
         * Gets the value of the orderExpireDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOrderExpireDateTime() {
            return orderExpireDateTime;
        }

        /**
         * Sets the value of the orderExpireDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOrderExpireDateTime(XMLGregorianCalendar value) {
            this.orderExpireDateTime = value;
        }

    }

    /**
     * @return the sessionid
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * @param sessionid the sessionid to set
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * @return the orderNumber
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * @param orderNumber the orderNumber to set
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

}
