//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import com.truteq.ccpgw.payment.gateway.api.soap.AdditionalDetailType;
import com.truteq.ccpgw.payment.gateway.api.soap.AddressType;
import com.truteq.ccpgw.payment.gateway.api.soap.AccountDetailType;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalTransaction" type="{}OriginalTransactionType" minOccurs="0"/>
 *         &lt;element name="AmountDetail" type="{}CurrencyAmountType" minOccurs="0"/>
 *         &lt;element name="RefundDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PaymentMethod" type="{}PaymentMethodType"/>
 *                   &lt;choice>
 *                     &lt;element name="PaymentCard" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;extension base="{}PaymentCardType">
 *                           &lt;/extension>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="BankAccount" type="{}AccountDetailType" minOccurs="0"/>
 *                   &lt;/choice>
 *                   &lt;element name="BillingAddress" type="{}AddressType" minOccurs="0"/>
 *                   &lt;element name="Documents" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Document" type="{}DocumentType" maxOccurs="99"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MerchantAccountCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RequestID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalTransaction",
    "amountDetail",
    "refundDetail",
    "additionalDetail"
})
@XmlRootElement(name = "CancelOrRefundRQ")
public class CancelOrRefundRQ {

    @XmlElement(name = "OriginalTransaction")
    protected OriginalTransactionType originalTransaction;
    @XmlElement(name = "AmountDetail")
    protected CurrencyAmountType amountDetail;
    @XmlElement(name = "RefundDetail")
    protected CancelOrRefundRQ.RefundDetail refundDetail;
    @XmlElement(name = "AdditionalDetail")
    protected AdditionalDetailType additionalDetail;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "MerchantAccountCode", required = true)
    protected String merchantAccountCode;
    @XmlAttribute(name = "RequestID")
    protected String requestID;

    /**
     * Gets the value of the originalTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalTransactionType }
     *     
     */
    public OriginalTransactionType getOriginalTransaction() {
        return originalTransaction;
    }

    /**
     * Sets the value of the originalTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalTransactionType }
     *     
     */
    public void setOriginalTransaction(OriginalTransactionType value) {
        this.originalTransaction = value;
    }

    /**
     * Gets the value of the amountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyAmountType }
     *     
     */
    public CurrencyAmountType getAmountDetail() {
        return amountDetail;
    }

    /**
     * Sets the value of the amountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyAmountType }
     *     
     */
    public void setAmountDetail(CurrencyAmountType value) {
        this.amountDetail = value;
    }

    /**
     * Gets the value of the refundDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CancelOrRefundRQ.RefundDetail }
     *     
     */
    public CancelOrRefundRQ.RefundDetail getRefundDetail() {
        return refundDetail;
    }

    /**
     * Sets the value of the refundDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CancelOrRefundRQ.RefundDetail }
     *     
     */
    public void setRefundDetail(CancelOrRefundRQ.RefundDetail value) {
        this.refundDetail = value;
    }

    /**
     * Gets the value of the additionalDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDetailType }
     *     
     */
    public AdditionalDetailType getAdditionalDetail() {
        return additionalDetail;
    }

    /**
     * Sets the value of the additionalDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDetailType }
     *     
     */
    public void setAdditionalDetail(AdditionalDetailType value) {
        this.additionalDetail = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the merchantAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAccountCode() {
        return merchantAccountCode;
    }

    /**
     * Sets the value of the merchantAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAccountCode(String value) {
        this.merchantAccountCode = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PaymentMethod" type="{}PaymentMethodType"/>
     *         &lt;choice>
     *           &lt;element name="PaymentCard" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;extension base="{}PaymentCardType">
     *                 &lt;/extension>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="BankAccount" type="{}AccountDetailType" minOccurs="0"/>
     *         &lt;/choice>
     *         &lt;element name="BillingAddress" type="{}AddressType" minOccurs="0"/>
     *         &lt;element name="Documents" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Document" type="{}DocumentType" maxOccurs="99"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentMethod",
        "paymentCard",
        "bankAccount",
        "billingAddress",
        "documents"
    })
    public static class RefundDetail {

        @XmlElement(name = "PaymentMethod", required = true)
        protected PaymentMethodType paymentMethod;
        @XmlElement(name = "PaymentCard")
        protected CancelOrRefundRQ.RefundDetail.PaymentCard paymentCard;
        @XmlElement(name = "BankAccount")
        protected AccountDetailType bankAccount;
        @XmlElement(name = "BillingAddress")
        protected AddressType billingAddress;
        @XmlElement(name = "Documents")
        protected CancelOrRefundRQ.RefundDetail.Documents documents;

        /**
         * Gets the value of the paymentMethod property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentMethodType }
         *     
         */
        public PaymentMethodType getPaymentMethod() {
            return paymentMethod;
        }

        /**
         * Sets the value of the paymentMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentMethodType }
         *     
         */
        public void setPaymentMethod(PaymentMethodType value) {
            this.paymentMethod = value;
        }

        /**
         * Gets the value of the paymentCard property.
         * 
         * @return
         *     possible object is
         *     {@link CancelOrRefundRQ.RefundDetail.PaymentCard }
         *     
         */
        public CancelOrRefundRQ.RefundDetail.PaymentCard getPaymentCard() {
            return paymentCard;
        }

        /**
         * Sets the value of the paymentCard property.
         * 
         * @param value
         *     allowed object is
         *     {@link CancelOrRefundRQ.RefundDetail.PaymentCard }
         *     
         */
        public void setPaymentCard(CancelOrRefundRQ.RefundDetail.PaymentCard value) {
            this.paymentCard = value;
        }

        /**
         * Gets the value of the bankAccount property.
         * 
         * @return
         *     possible object is
         *     {@link AccountDetailType }
         *     
         */
        public AccountDetailType getBankAccount() {
            return bankAccount;
        }

        /**
         * Sets the value of the bankAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link AccountDetailType }
         *     
         */
        public void setBankAccount(AccountDetailType value) {
            this.bankAccount = value;
        }

        /**
         * Gets the value of the billingAddress property.
         * 
         * @return
         *     possible object is
         *     {@link AddressType }
         *     
         */
        public AddressType getBillingAddress() {
            return billingAddress;
        }

        /**
         * Sets the value of the billingAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressType }
         *     
         */
        public void setBillingAddress(AddressType value) {
            this.billingAddress = value;
        }

        /**
         * Gets the value of the documents property.
         * 
         * @return
         *     possible object is
         *     {@link CancelOrRefundRQ.RefundDetail.Documents }
         *     
         */
        public CancelOrRefundRQ.RefundDetail.Documents getDocuments() {
            return documents;
        }

        /**
         * Sets the value of the documents property.
         * 
         * @param value
         *     allowed object is
         *     {@link CancelOrRefundRQ.RefundDetail.Documents }
         *     
         */
        public void setDocuments(CancelOrRefundRQ.RefundDetail.Documents value) {
            this.documents = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Document" type="{}DocumentType" maxOccurs="99"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "document"
        })
        public static class Documents {

            @XmlElement(name = "Document", required = true)
            protected List<DocumentType> document;

            /**
             * Gets the value of the document property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the document property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDocument().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocumentType }
             * 
             * 
             */
            public List<DocumentType> getDocument() {
                if (document == null) {
                    document = new ArrayList<DocumentType>();
                }
                return this.document;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}PaymentCardType">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PaymentCard
            extends PaymentCardType
        {


        }

    }

}
