//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import com.truteq.ccpgw.payment.gateway.api.soap.AdditionalDetailType;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalTransaction" type="{}OriginalTransactionType"/>
 *         &lt;element name="CaptureDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PassengerDetail" type="{}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
 *                   &lt;element name="FlightDetail" type="{}FlightDetailType" maxOccurs="20" minOccurs="0"/>
 *                   &lt;element name="CaptureAmount" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}CurrencyAmountType">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MerchantAccountCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RequestID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originalTransaction",
    "captureDetail"
})
@XmlRootElement(name = "CaptureRQ")
public class CaptureRQ {

    @XmlElement(name = "OriginalTransaction", required = true)
    protected OriginalTransactionType originalTransaction;
    @XmlElement(name = "CaptureDetail")
    protected CaptureRQ.CaptureDetail captureDetail;
    @XmlAttribute(name = "Version", required = true)
    protected String version;
    @XmlAttribute(name = "MerchantAccountCode", required = true)
    protected String merchantAccountCode;
    @XmlAttribute(name = "RequestID")
    protected String requestID;

    /**
     * Gets the value of the originalTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link OriginalTransactionType }
     *     
     */
    public OriginalTransactionType getOriginalTransaction() {
        return originalTransaction;
    }

    /**
     * Sets the value of the originalTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginalTransactionType }
     *     
     */
    public void setOriginalTransaction(OriginalTransactionType value) {
        this.originalTransaction = value;
    }

    /**
     * Gets the value of the captureDetail property.
     * 
     * @return
     *     possible object is
     *     {@link CaptureRQ.CaptureDetail }
     *     
     */
    public CaptureRQ.CaptureDetail getCaptureDetail() {
        return captureDetail;
    }

    /**
     * Sets the value of the captureDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaptureRQ.CaptureDetail }
     *     
     */
    public void setCaptureDetail(CaptureRQ.CaptureDetail value) {
        this.captureDetail = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the merchantAccountCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantAccountCode() {
        return merchantAccountCode;
    }

    /**
     * Sets the value of the merchantAccountCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantAccountCode(String value) {
        this.merchantAccountCode = value;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PassengerDetail" type="{}PassengerDetailType" maxOccurs="99" minOccurs="0"/>
     *         &lt;element name="FlightDetail" type="{}FlightDetailType" maxOccurs="20" minOccurs="0"/>
     *         &lt;element name="CaptureAmount" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}CurrencyAmountType">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AdditionalDetail" type="{}AdditionalDetailType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passengerDetail",
        "flightDetail",
        "captureAmount",
        "additionalDetail"
    })
    public static class CaptureDetail {

        @XmlElement(name = "PassengerDetail")
        protected List<PassengerDetailType> passengerDetail;
        @XmlElement(name = "FlightDetail")
        protected List<FlightDetailType> flightDetail;
        @XmlElement(name = "CaptureAmount")
        protected CaptureRQ.CaptureDetail.CaptureAmount captureAmount;
        @XmlElement(name = "AdditionalDetail")
        protected AdditionalDetailType additionalDetail;

        /**
         * Gets the value of the passengerDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the passengerDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPassengerDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PassengerDetailType }
         * 
         * 
         */
        public List<PassengerDetailType> getPassengerDetail() {
            if (passengerDetail == null) {
                passengerDetail = new ArrayList<PassengerDetailType>();
            }
            return this.passengerDetail;
        }

        /**
         * Gets the value of the flightDetail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flightDetail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlightDetail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FlightDetailType }
         * 
         * 
         */
        public List<FlightDetailType> getFlightDetail() {
            if (flightDetail == null) {
                flightDetail = new ArrayList<FlightDetailType>();
            }
            return this.flightDetail;
        }

        /**
         * Gets the value of the captureAmount property.
         * 
         * @return
         *     possible object is
         *     {@link CaptureRQ.CaptureDetail.CaptureAmount }
         *     
         */
        public CaptureRQ.CaptureDetail.CaptureAmount getCaptureAmount() {
            return captureAmount;
        }

        /**
         * Sets the value of the captureAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaptureRQ.CaptureDetail.CaptureAmount }
         *     
         */
        public void setCaptureAmount(CaptureRQ.CaptureDetail.CaptureAmount value) {
            this.captureAmount = value;
        }

        /**
         * Gets the value of the additionalDetail property.
         * 
         * @return
         *     possible object is
         *     {@link AdditionalDetailType }
         *     
         */
        public AdditionalDetailType getAdditionalDetail() {
            return additionalDetail;
        }

        /**
         * Sets the value of the additionalDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link AdditionalDetailType }
         *     
         */
        public void setAdditionalDetail(AdditionalDetailType value) {
            this.additionalDetail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}CurrencyAmountType">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CaptureAmount
            extends CurrencyAmountType
        {


        }

    }

}
