//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Dynamic Currency Conversion
 * 
 * <p>Java class for DCCType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCCType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SaleAmountDetail" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}CurrencyAmountType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="OptedIn" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="SupplierID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SupplierTransID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExchangeRate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="OfferDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="OfferTimeZoneOffsetFromUTC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCCType", propOrder = {
    "saleAmountDetail"
})
public class DCCType {

    @XmlElement(name = "SaleAmountDetail")
    protected DCCType.SaleAmountDetail saleAmountDetail;
    @XmlAttribute(name = "OptedIn")
    protected Boolean optedIn;
    @XmlAttribute(name = "SupplierID")
    protected String supplierID;
    @XmlAttribute(name = "MerchantID")
    protected String merchantID;
    @XmlAttribute(name = "Type")
    protected String type;
    @XmlAttribute(name = "SupplierTransID")
    protected String supplierTransID;
    @XmlAttribute(name = "ExchangeRate")
    protected String exchangeRate;
    @XmlAttribute(name = "OfferDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar offerDateTime;
    @XmlAttribute(name = "OfferTimeZoneOffsetFromUTC")
    protected String offerTimeZoneOffsetFromUTC;

    /**
     * Gets the value of the saleAmountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link DCCType.SaleAmountDetail }
     *     
     */
    public DCCType.SaleAmountDetail getSaleAmountDetail() {
        return saleAmountDetail;
    }

    /**
     * Sets the value of the saleAmountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link DCCType.SaleAmountDetail }
     *     
     */
    public void setSaleAmountDetail(DCCType.SaleAmountDetail value) {
        this.saleAmountDetail = value;
    }

    /**
     * Gets the value of the optedIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptedIn() {
        return optedIn;
    }

    /**
     * Sets the value of the optedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptedIn(Boolean value) {
        this.optedIn = value;
    }

    /**
     * Gets the value of the supplierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierID() {
        return supplierID;
    }

    /**
     * Sets the value of the supplierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierID(String value) {
        this.supplierID = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the supplierTransID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierTransID() {
        return supplierTransID;
    }

    /**
     * Sets the value of the supplierTransID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierTransID(String value) {
        this.supplierTransID = value;
    }

    /**
     * Gets the value of the exchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeRate() {
        return exchangeRate;
    }

    /**
     * Sets the value of the exchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeRate(String value) {
        this.exchangeRate = value;
    }

    /**
     * Gets the value of the offerDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferDateTime() {
        return offerDateTime;
    }

    /**
     * Sets the value of the offerDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferDateTime(XMLGregorianCalendar value) {
        this.offerDateTime = value;
    }

    /**
     * Gets the value of the offerTimeZoneOffsetFromUTC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferTimeZoneOffsetFromUTC() {
        return offerTimeZoneOffsetFromUTC;
    }

    /**
     * Sets the value of the offerTimeZoneOffsetFromUTC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferTimeZoneOffsetFromUTC(String value) {
        this.offerTimeZoneOffsetFromUTC = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}CurrencyAmountType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SaleAmountDetail
        extends CurrencyAmountType
    {


    }

}
