//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.truteq.ipgw.frontend.adapter.sabre.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.truteq.ipgw.frontend.adapter.sabre.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelOrRefundRQ }
     * 
     * @return 
     */
    public CancelOrRefundRQ createCancelOrRefundRQ() {
        return new CancelOrRefundRQ();
    }

    /**
     * Create an instance of {@link AuthRQ }
     * 
     */
    public AuthRQ createAuthRQ() {
        return new AuthRQ();
    }

    /**
     * Create an instance of {@link PaymentMethodsRS }
     * 
     */
    public PaymentMethodsRS createPaymentMethodsRS() {
        return new PaymentMethodsRS();
    }

    /**
     * Create an instance of {@link CaptureRQ }
     * 
     */
    public CaptureRQ createCaptureRQ() {
        return new CaptureRQ();
    }

    /**
     * Create an instance of {@link AuthRS }
     * 
     */
    public AuthRS createAuthRS() {
        return new AuthRS();
    }

    /**
     * Create an instance of {@link TokensType }
     * 
     */
    public TokensType createTokensType() {
        return new TokensType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PersonIDType }
     * 
     */
    public PersonIDType createPersonIDType() {
        return new PersonIDType();
    }

    /**
     * Create an instance of {@link PassengerDetailType }
     * 
     */
    public PassengerDetailType createPassengerDetailType() {
        return new PassengerDetailType();
    }

    /**
     * Create an instance of {@link DCCType }
     * 
     */
    public DCCType createDCCType() {
        return new DCCType();
    }

    /**
     * Create an instance of {@link FlightDetailType }
     * 
     */
    public FlightDetailType createFlightDetailType() {
        return new FlightDetailType();
    }

    /**
     * Create an instance of {@link PaymentCardType }
     * 
     */
    public PaymentCardType createPaymentCardType() {
        return new PaymentCardType();
    }

    /**
     * Create an instance of {@link ProductDetailType }
     * 
     */
    public ProductDetailType createProductDetailType() {
        return new ProductDetailType();
    }

    /**
     * Create an instance of {@link CaptureRQ.CaptureDetail }
     * 
     */
    public CaptureRQ.CaptureDetail createCaptureRQCaptureDetail() {
        return new CaptureRQ.CaptureDetail();
    }

    /**
     * Create an instance of {@link PaymentMethodsRS.PaymentMethods }
     * 
     */
    public PaymentMethodsRS.PaymentMethods createPaymentMethodsRSPaymentMethods() {
        return new PaymentMethodsRS.PaymentMethods();
    }

    /**
     * Create an instance of {@link PaymentMethodsRS.PaymentMethods.PaymentMethod }
     * 
     */
    public PaymentMethodsRS.PaymentMethods.PaymentMethod createPaymentMethodsRSPaymentMethodsPaymentMethod() {
        return new PaymentMethodsRS.PaymentMethods.PaymentMethod();
    }

    /**
     * Create an instance of {@link PaymentDetailType }
     * 
     */
    public PaymentDetailType createPaymentDetailType() {
        return new PaymentDetailType();
    }

    /**
     * Create an instance of {@link POSType }
     * 
     */
    public POSType createPOSType() {
        return new POSType();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail }
     * 
     */
    public POSType.BrowserDetail createPOSTypeBrowserDetail() {
        return new POSType.BrowserDetail();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail.HttpHeaders }
     * 
     */
    public POSType.BrowserDetail.HttpHeaders createPOSTypeBrowserDetailHttpHeaders() {
        return new POSType.BrowserDetail.HttpHeaders();
    }

    /**
     * Create an instance of {@link AdditionalDetailType }
     * 
     */
    public AdditionalDetailType createAdditionalDetailType() {
        return new AdditionalDetailType();
    }

    /**
     * Create an instance of {@link CancelOrRefundRQ.RefundDetail }
     * 
     */
    public CancelOrRefundRQ.RefundDetail createCancelOrRefundRQRefundDetail() {
        return new CancelOrRefundRQ.RefundDetail();
    }

    /**
     * Create an instance of {@link PaymentMethodsRQ }
     * 
     */
    public PaymentMethodsRQ createPaymentMethodsRQ() {
        return new PaymentMethodsRQ();
    }

    /**
     * Create an instance of {@link OriginalTransactionType }
     * 
     */
    public OriginalTransactionType createOriginalTransactionType() {
        return new OriginalTransactionType();
    }

    /**
     * Create an instance of {@link CurrencyAmountType }
     * 
     */
    public CurrencyAmountType createCurrencyAmountType() {
        return new CurrencyAmountType();
    }

    /**
     * Create an instance of {@link CancelOrRefundRS }
     * 
     */
    public CancelOrRefundRS createCancelOrRefundRS() {
        return new CancelOrRefundRS();
    }

    /**
     * Create an instance of {@link AuthRQ.OrderDetail }
     * 
     */
    public AuthRQ.OrderDetail createAuthRQOrderDetail() {
        return new AuthRQ.OrderDetail();
    }

    /**
     * Create an instance of {@link CustomerDetailType }
     * 
     */
    public CustomerDetailType createCustomerDetailType() {
        return new CustomerDetailType();
    }

    /**
     * Create an instance of {@link CaptureRS }
     * 
     */
    public CaptureRS createCaptureRS() {
        return new CaptureRS();
    }

    /**
     * Create an instance of {@link AuthRS.T3DSResult }
     * 
     */
    public AuthRS.T3DSResult createAuthRST3DSResult() {
        return new AuthRS.T3DSResult();
    }

    /**
     * Create an instance of {@link AuthRS.CardReaderResult }
     * 
     */
    public AuthRS.CardReaderResult createAuthRSCardReaderResult() {
        return new AuthRS.CardReaderResult();
    }

    /**
     * Create an instance of {@link AuthRS.ListOfReferenceNbrs }
     * 
     */
    public AuthRS.ListOfReferenceNbrs createAuthRSListOfReferenceNbrs() {
        return new AuthRS.ListOfReferenceNbrs();
    }

    /**
     * Create an instance of {@link StreetNmbrType }
     * 
     */
    public StreetNmbrType createStreetNmbrType() {
        return new StreetNmbrType();
    }

    /**
     * Create an instance of {@link StateProvType }
     * 
     */
    public StateProvType createStateProvType() {
        return new StateProvType();
    }

    /**
     * Create an instance of {@link FeeBreakType }
     * 
     */
    public FeeBreakType createFeeBreakType() {
        return new FeeBreakType();
    }

    /**
     * Create an instance of {@link PaymentMethodType }
     * 
     */
    public PaymentMethodType createPaymentMethodType() {
        return new PaymentMethodType();
    }

    /**
     * Create an instance of {@link ReturnURLsType }
     * 
     */
    public ReturnURLsType createReturnURLsType() {
        return new ReturnURLsType();
    }

    /**
     * Create an instance of {@link IssuerType }
     * 
     */
    public IssuerType createIssuerType() {
        return new IssuerType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link AccountDetailType }
     * 
     */
    public AccountDetailType createAccountDetailType() {
        return new AccountDetailType();
    }

    /**
     * Create an instance of {@link CountryNameType }
     * 
     */
    public CountryNameType createCountryNameType() {
        return new CountryNameType();
    }

    /**
     * Create an instance of {@link ProductDetailItemType }
     * 
     */
    public ProductDetailItemType createProductDetailItemType() {
        return new ProductDetailItemType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link PhoneType }
     * 
     */
    public PhoneType createPhoneType() {
        return new PhoneType();
    }

    /**
     * Create an instance of {@link ReferenceNbrType }
     * 
     */
    public ReferenceNbrType createReferenceNbrType() {
        return new ReferenceNbrType();
    }

    /**
     * Create an instance of {@link TokensType.Token }
     * 
     */
    public TokensType.Token createTokensTypeToken() {
        return new TokensType.Token();
    }

    /**
     * Create an instance of {@link AddressType.StateProv }
     * 
     */
    public AddressType.StateProv createAddressTypeStateProv() {
        return new AddressType.StateProv();
    }

    /**
     * Create an instance of {@link PersonIDType.Passport }
     * 
     */
    public PersonIDType.Passport createPersonIDTypePassport() {
        return new PersonIDType.Passport();
    }

    /**
     * Create an instance of {@link PersonIDType.Visa }
     * 
     */
    public PersonIDType.Visa createPersonIDTypeVisa() {
        return new PersonIDType.Visa();
    }

    /**
     * Create an instance of {@link PersonIDType.Other }
     * 
     */
    public PersonIDType.Other createPersonIDTypeOther() {
        return new PersonIDType.Other();
    }

    /**
     * Create an instance of {@link PassengerDetailType.Document }
     * 
     */
    public PassengerDetailType.Document createPassengerDetailTypeDocument() {
        return new PassengerDetailType.Document();
    }

    /**
     * Create an instance of {@link DCCType.SaleAmountDetail }
     * 
     */
    public DCCType.SaleAmountDetail createDCCTypeSaleAmountDetail() {
        return new DCCType.SaleAmountDetail();
    }

    /**
     * Create an instance of {@link FlightDetailType.DepartureInfo }
     * 
     */
    public FlightDetailType.DepartureInfo createFlightDetailTypeDepartureInfo() {
        return new FlightDetailType.DepartureInfo();
    }

    /**
     * Create an instance of {@link FlightDetailType.ArrivalInfo }
     * 
     */
    public FlightDetailType.ArrivalInfo createFlightDetailTypeArrivalInfo() {
        return new FlightDetailType.ArrivalInfo();
    }

    /**
     * Create an instance of {@link PaymentCardType.T3DS }
     * 
     */
    public PaymentCardType.T3DS createPaymentCardTypeT3DS() {
        return new PaymentCardType.T3DS();
    }

    /**
     * Create an instance of {@link PaymentCardType.CardReader }
     * 
     */
    public PaymentCardType.CardReader createPaymentCardTypeCardReader() {
        return new PaymentCardType.CardReader();
    }

    /**
     * Create an instance of {@link ProductDetailType.ProductDetailItems }
     * 
     */
    public ProductDetailType.ProductDetailItems createProductDetailTypeProductDetailItems() {
        return new ProductDetailType.ProductDetailItems();
    }

    /**
     * Create an instance of {@link CaptureRQ.CaptureDetail.CaptureAmount }
     * 
     */
    public CaptureRQ.CaptureDetail.CaptureAmount createCaptureRQCaptureDetailCaptureAmount() {
        return new CaptureRQ.CaptureDetail.CaptureAmount();
    }

    /**
     * Create an instance of {@link PaymentMethodsRS.PaymentMethods.PaymentMethod.Issuers }
     * 
     */
    public PaymentMethodsRS.PaymentMethods.PaymentMethod.Issuers createPaymentMethodsRSPaymentMethodsPaymentMethodIssuers() {
        return new PaymentMethodsRS.PaymentMethods.PaymentMethod.Issuers();
    }

    /**
     * Create an instance of {@link PaymentDetailType.PaymentCard }
     * 
     */
    public PaymentDetailType.PaymentCard createPaymentDetailTypePaymentCard() {
        return new PaymentDetailType.PaymentCard();
    }

    /**
     * Create an instance of {@link PaymentDetailType.AmountDetail }
     * 
     */
    public PaymentDetailType.AmountDetail createPaymentDetailTypeAmountDetail() {
        return new PaymentDetailType.AmountDetail();
    }

    /**
     * Create an instance of {@link PaymentDetailType.InstallmentDetail }
     * 
     */
    public PaymentDetailType.InstallmentDetail createPaymentDetailTypeInstallmentDetail() {
        return new PaymentDetailType.InstallmentDetail();
    }

    /**
     * Create an instance of {@link POSType.BrowserDetail.HttpHeaders.HttpHeader }
     * 
     */
    public POSType.BrowserDetail.HttpHeaders.HttpHeader createPOSTypeBrowserDetailHttpHeadersHttpHeader() {
        return new POSType.BrowserDetail.HttpHeaders.HttpHeader();
    }

    /**
     * Create an instance of {@link AdditionalDetailType.Field }
     * 
     */
    public AdditionalDetailType.Field createAdditionalDetailTypeField() {
        return new AdditionalDetailType.Field();
    }

    /**
     * Create an instance of {@link CancelOrRefundRQ.RefundDetail.PaymentCard }
     * 
     */
    public CancelOrRefundRQ.RefundDetail.PaymentCard createCancelOrRefundRQRefundDetailPaymentCard() {
        return new CancelOrRefundRQ.RefundDetail.PaymentCard();
    }

    /**
     * Create an instance of {@link CancelOrRefundRQ.RefundDetail.Documents }
     * 
     */
    public CancelOrRefundRQ.RefundDetail.Documents createCancelOrRefundRQRefundDetailDocuments() {
        return new CancelOrRefundRQ.RefundDetail.Documents();
    }

}
