//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.26 at 04:22:56 PM AEST 
//


package com.truteq.ccpgw.payment.gateway.api.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Identification about a specific credit card
 * 
 * <p>Java class for PaymentCardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentCardType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="T3DS" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CAVV" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CAVV_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ECI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="XID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="VerificationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="AuthenticationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PA_Response" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DirectoryServerTrxID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplePayCryptogram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardReader" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}TokensType">
 *                 &lt;attribute name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="ChipCardInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CardNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IssueNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CVC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CardHolderName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ReadyFor3DSVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentCardType", propOrder = {
    "t3DS",
    "applePayCryptogram",
    "cardReader"
})
@XmlSeeAlso({
    com.truteq.ccpgw.payment.gateway.api.soap.CancelOrRefundRQ.RefundDetail.PaymentCard.class,
    com.truteq.ccpgw.payment.gateway.api.soap.PaymentDetailType.PaymentCard.class
})
public class PaymentCardType {

    @XmlElement(name = "T3DS")
    protected PaymentCardType.T3DS t3DS;
    @XmlElement(name = "ApplePayCryptogram")
    protected String applePayCryptogram;
    @XmlElement(name = "CardReader")
    protected PaymentCardType.CardReader cardReader;
    @XmlAttribute(name = "CardNumber", required = true)
    protected String cardNumber;
    @XmlAttribute(name = "IssueNumber")
    protected String issueNumber;
    @XmlAttribute(name = "CVC")
    protected String cvc;
    @XmlAttribute(name = "EffectiveDate")
    protected String effectiveDate;
    @XmlAttribute(name = "ExpireDate")
    protected String expireDate;
    @XmlAttribute(name = "CardHolderName")
    protected String cardHolderName;
    @XmlAttribute(name = "ReadyFor3DSVersion")
    protected String readyFor3DSVersion;

    /**
     * Gets the value of the t3DS property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.T3DS }
     *     
     */
    public PaymentCardType.T3DS getT3DS() {
        return t3DS;
    }

    /**
     * Sets the value of the t3DS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.T3DS }
     *     
     */
    public void setT3DS(PaymentCardType.T3DS value) {
        this.t3DS = value;
    }

    /**
     * Gets the value of the applePayCryptogram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplePayCryptogram() {
        return applePayCryptogram;
    }

    /**
     * Sets the value of the applePayCryptogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplePayCryptogram(String value) {
        this.applePayCryptogram = value;
    }

    /**
     * Gets the value of the cardReader property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentCardType.CardReader }
     *     
     */
    public PaymentCardType.CardReader getCardReader() {
        return cardReader;
    }

    /**
     * Sets the value of the cardReader property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentCardType.CardReader }
     *     
     */
    public void setCardReader(PaymentCardType.CardReader value) {
        this.cardReader = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the cvc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVC() {
        return cvc;
    }

    /**
     * Sets the value of the cvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVC(String value) {
        this.cvc = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the cardHolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderName() {
        return cardHolderName;
    }

    /**
     * Sets the value of the cardHolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderName(String value) {
        this.cardHolderName = value;
    }

    /**
     * Gets the value of the readyFor3DSVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadyFor3DSVersion() {
        return readyFor3DSVersion;
    }

    /**
     * Sets the value of the readyFor3DSVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadyFor3DSVersion(String value) {
        this.readyFor3DSVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}TokensType">
     *       &lt;attribute name="DeviceType" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DeviceID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ChipCardInd" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CardReader
        extends TokensType
    {

        @XmlAttribute(name = "DeviceType")
        protected String deviceType;
        @XmlAttribute(name = "DeviceID")
        protected String deviceID;
        @XmlAttribute(name = "ChipCardInd")
        protected Boolean chipCardInd;

        /**
         * Gets the value of the deviceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceType() {
            return deviceType;
        }

        /**
         * Sets the value of the deviceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceType(String value) {
            this.deviceType = value;
        }

        /**
         * Gets the value of the deviceID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeviceID() {
            return deviceID;
        }

        /**
         * Sets the value of the deviceID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeviceID(String value) {
            this.deviceID = value;
        }

        /**
         * Gets the value of the chipCardInd property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isChipCardInd() {
            return chipCardInd;
        }

        /**
         * Sets the value of the chipCardInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setChipCardInd(Boolean value) {
            this.chipCardInd = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CAVV" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CAVV_Algorithm" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="ECI" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="XID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="VerificationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="AuthenticationResult" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MD" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PA_Response" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="DirectoryServerTrxID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class T3DS {

        @XmlAttribute(name = "CAVV")
        protected String cavv;
        @XmlAttribute(name = "CAVV_Algorithm")
        protected String cavvAlgorithm;
        @XmlAttribute(name = "ECI")
        protected String eci;
        @XmlAttribute(name = "XID")
        protected String xid;
        @XmlAttribute(name = "VerificationResult")
        protected String verificationResult;
        @XmlAttribute(name = "AuthenticationResult")
        protected String authenticationResult;
        @XmlAttribute(name = "MD")
        protected String md;
        @XmlAttribute(name = "PA_Response")
        protected String paResponse;
        @XmlAttribute(name = "DirectoryServerTrxID")
        protected String directoryServerTrxID;
        @XmlAttribute(name = "Version")
        protected String version;

        /**
         * Gets the value of the cavv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVV() {
            return cavv;
        }

        /**
         * Sets the value of the cavv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVV(String value) {
            this.cavv = value;
        }

        /**
         * Gets the value of the cavvAlgorithm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCAVVAlgorithm() {
            return cavvAlgorithm;
        }

        /**
         * Sets the value of the cavvAlgorithm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCAVVAlgorithm(String value) {
            this.cavvAlgorithm = value;
        }

        /**
         * Gets the value of the eci property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getECI() {
            return eci;
        }

        /**
         * Sets the value of the eci property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setECI(String value) {
            this.eci = value;
        }

        /**
         * Gets the value of the xid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXID() {
            return xid;
        }

        /**
         * Sets the value of the xid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXID(String value) {
            this.xid = value;
        }

        /**
         * Gets the value of the verificationResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVerificationResult() {
            return verificationResult;
        }

        /**
         * Sets the value of the verificationResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVerificationResult(String value) {
            this.verificationResult = value;
        }

        /**
         * Gets the value of the authenticationResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthenticationResult() {
            return authenticationResult;
        }

        /**
         * Sets the value of the authenticationResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthenticationResult(String value) {
            this.authenticationResult = value;
        }

        /**
         * Gets the value of the md property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMD() {
            return md;
        }

        /**
         * Sets the value of the md property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMD(String value) {
            this.md = value;
        }

        /**
         * Gets the value of the paResponse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPAResponse() {
            return paResponse;
        }

        /**
         * Sets the value of the paResponse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPAResponse(String value) {
            this.paResponse = value;
        }

        /**
         * Gets the value of the directoryServerTrxID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDirectoryServerTrxID() {
            return directoryServerTrxID;
        }

        /**
         * Sets the value of the directoryServerTrxID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDirectoryServerTrxID(String value) {
            this.directoryServerTrxID = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

    }

}
