//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 01:49:42 PM AEST 
//


package com.truteq.ccpgw.netcetera.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Invalid request data.
 *       
 * 
 * <p>Java class for IReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IReq">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iReqCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="iReqDetail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vendorCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IReq", propOrder = {
    "iReqCode",
    "iReqDetail",
    "vendorCode"
})
public class IReq {

    @XmlElement(required = true)
    protected String iReqCode;
    protected String iReqDetail;
    protected String vendorCode;

    /**
     * Gets the value of the iReqCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIReqCode() {
        return iReqCode;
    }

    /**
     * Sets the value of the iReqCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIReqCode(String value) {
        this.iReqCode = value;
    }

    /**
     * Gets the value of the iReqDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIReqDetail() {
        return iReqDetail;
    }

    /**
     * Sets the value of the iReqDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIReqDetail(String value) {
        this.iReqDetail = value;
    }

    /**
     * Gets the value of the vendorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorCode() {
        return vendorCode;
    }

    /**
     * Sets the value of the vendorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorCode(String value) {
        this.vendorCode = value;
    }

}
