//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 01:49:42 PM AEST 
//


package com.truteq.ccpgw.netcetera.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.truteq.ccpgw.netcetera.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ThreeDSecure_QNAME = new QName("", "ThreeDSecure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.truteq.ccpgw.netcetera.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PaResValidationResponse }
     * 
     */
    public PaResValidationResponse createPaResValidationResponse() {
        return new PaResValidationResponse();
    }

    /**
     * Create an instance of {@link ThreeDSecureType }
     * 
     */
    public ThreeDSecureType createThreeDSecureType() {
        return new ThreeDSecureType();
    }

    /**
     * Create an instance of {@link ErrorDetails }
     * 
     */
    public ErrorDetails createErrorDetails() {
        return new ErrorDetails();
    }

    /**
     * Create an instance of {@link PaReqCreationRequest }
     * 
     */
    public PaReqCreationRequest createPaReqCreationRequest() {
        return new PaReqCreationRequest();
    }

    /**
     * Create an instance of {@link Cardholder }
     * 
     */
    public Cardholder createCardholder() {
        return new Cardholder();
    }

    /**
     * Create an instance of {@link Purchase }
     * 
     */
    public Purchase createPurchase() {
        return new Purchase();
    }

    /**
     * Create an instance of {@link Merchant }
     * 
     */
    public Merchant createMerchant() {
        return new Merchant();
    }

    /**
     * Create an instance of {@link Browser }
     * 
     */
    public Browser createBrowser() {
        return new Browser();
    }

    /**
     * Create an instance of {@link PaReqCreationResponse }
     * 
     */
    public PaReqCreationResponse createPaReqCreationResponse() {
        return new PaReqCreationResponse();
    }

    /**
     * Create an instance of {@link SessionData }
     * 
     */
    public SessionData createSessionData() {
        return new SessionData();
    }

    /**
     * Create an instance of {@link PaResValidationRequest }
     * 
     */
    public PaResValidationRequest createPaResValidationRequest() {
        return new PaResValidationRequest();
    }

    /**
     * Create an instance of {@link Recur }
     * 
     */
    public Recur createRecur() {
        return new Recur();
    }

    /**
     * Create an instance of {@link VEReq }
     * 
     */
    public VEReq createVEReq() {
        return new VEReq();
    }

    /**
     * Create an instance of {@link Merchant2 }
     * 
     */
    public Merchant2 createMerchant2() {
        return new Merchant2();
    }

    /**
     * Create an instance of {@link Browser2 }
     * 
     */
    public Browser2 createBrowser2() {
        return new Browser2();
    }

    /**
     * Create an instance of {@link PARes }
     * 
     */
    public PARes createPARes() {
        return new PARes();
    }

    /**
     * Create an instance of {@link Purchase2 }
     * 
     */
    public Purchase2 createPurchase2() {
        return new Purchase2();
    }

    /**
     * Create an instance of {@link TX }
     * 
     */
    public TX createTX() {
        return new TX();
    }

    /**
     * Create an instance of {@link IReq }
     * 
     */
    public IReq createIReq() {
        return new IReq();
    }

    /**
     * Create an instance of {@link PAReq }
     * 
     */
    public PAReq createPAReq() {
        return new PAReq();
    }

    /**
     * Create an instance of {@link CH }
     * 
     */
    public CH createCH() {
        return new CH();
    }

    /**
     * Create an instance of {@link VERes }
     * 
     */
    public VERes createVERes() {
        return new VERes();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Recur2 }
     * 
     */
    public Recur2 createRecur2() {
        return new Recur2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ThreeDSecureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ThreeDSecure")
    public JAXBElement<ThreeDSecureType> createThreeDSecure(ThreeDSecureType value) {
        return new JAXBElement<ThreeDSecureType>(_ThreeDSecure_QNAME, ThreeDSecureType.class, null, value);
    }

}
