//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 01:49:42 PM AEST 
//


package com.truteq.ccpgw.netcetera.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *           
 *             The response returned from the createPaReqIfEnrolled call.
 *           
 *         
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sessionId" type="{http://mpi.netcetera.com}SessionId"/>
 *         &lt;element name="SessionData" type="{http://mpi.netcetera.com}SessionData" minOccurs="0"/>
 *         &lt;element name="PaReq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThreeDSecureVEReq" type="{}ThreeDSecureType" minOccurs="0"/>
 *         &lt;element name="ThreeDSecureVERes" type="{}ThreeDSecureType" minOccurs="0"/>
 *         &lt;element name="Error" type="{http://mpi.netcetera.com/common}ErrorDetails" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionId",
    "SessionData",
    "PaReq",
    "ThreeDSecureVEReq",
    "ThreeDSecureVERes",
    "error"
})
@XmlRootElement(name = "PaReqCreationResponse", namespace = "http://mpi.netcetera.com")
public class PaReqCreationResponse {

    @XmlElement(required = true)
    protected String sessionId;
    @XmlElement(name = "SessionData")
    protected SessionData SessionData;
    @XmlElement(name = "PaReq")
    protected String PaReq;
    @XmlElement(name = "ThreeDSecureVEReq")
    protected ThreeDSecureType ThreeDSecureVEReq;
    @XmlElement(name = "ThreeDSecureVERes")
    protected ThreeDSecureType ThreeDSecureVERes;
    @XmlElement(name = "Error")
    protected ErrorDetails Error;


    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

    /**
     * Gets the value of the SessionData property.
     * 
     * @return
     *     possible object is
     *     {@link SessionData }
     *     
     */
    public SessionData getSessionData() {
        return SessionData;
    }

    /**
     * Sets the value of the SessionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionData }
     *     
     */
    public void setSessionData(SessionData value) {
        this.SessionData = value;
    }

    /**
     * Gets the value of the PaReq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaReq() {
        return PaReq;
    }

    /**
     * Sets the value of the PaReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaReq(String value) {
        this.PaReq = value;
    }

    /**
     * Gets the value of the ThreeDSecureVEReq property.
     * 
     * @return
     *     possible object is
     *     {@link ThreeDSecureType }
     *     
     */
    public ThreeDSecureType getThreeDSecureVEReq() {
        return ThreeDSecureVEReq;
    }

    /**
     * Sets the value of the ThreeDSecureVEReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThreeDSecureType }
     *     
     */
    public void setThreeDSecureVEReq(ThreeDSecureType value) {
        this.ThreeDSecureVEReq = value;
    }

    /**
     * Gets the value of the ThreeDSecureVERes property.
     * 
     * @return
     *     possible object is
     *     {@link ThreeDSecureType }
     *     
     */
    public ThreeDSecureType getThreeDSecureVERes() {
        return ThreeDSecureVERes;
    }

    /**
     * Sets the value of the ThreeDSecureVERes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThreeDSecureType }
     *     
     */
    public void setThreeDSecureVERes(ThreeDSecureType value) {
        this.ThreeDSecureVERes = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorDetails }
     *     
     */
    public ErrorDetails getError() {
        return Error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorDetails }
     *     
     */
    public void setError(ErrorDetails value) {
        this.Error = value;
    }

}
