//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 01:49:42 PM AEST 
//


package com.truteq.ccpgw.netcetera.model;

import com.google.gson.Gson;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *           
 *             The PaResValidationRequest passed to MPI for the validatePaRes call.
 *           
 *         
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaRes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SessionData" type="{http://mpi.netcetera.com}SessionData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paRes",
    "sessionData"
})
@XmlRootElement(name = "PaResValidationRequest", namespace = "http://mpi.netcetera.com")
public class PaResValidationRequest {

    @XmlElement(name = "PaRes")
    protected String PaRes;
    @XmlElement(name = "SessionData")
    protected SessionData SessionData;
    
    
    public String toJSON(){
        Gson gson =new Gson();
        return gson.toJson(this);
    }    

    /**
     * Gets the value of the paRes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaRes() {
        return PaRes;
    }

    /**
     * Sets the value of the paRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaRes(String value) {
        this.PaRes = value;
    }

    /**
     * Gets the value of the sessionData property.
     * 
     * @return
     *     possible object is
     *     {@link SessionData }
     *     
     */
    public SessionData getSessionData() {
        return SessionData;
    }

    /**
     * Sets the value of the sessionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionData }
     *     
     */
    public void setSessionData(SessionData value) {
        this.SessionData = value;
    }

}
